### ISSUE TITLE
bug：RegexEventSerializer 字段丢失

### ISSUE THREAD

**Issue by likewindcai** [aliyun/aliyun-log-flume#13]
line 117： i **>=** fieldNames.size()，导致字段少了一个。
`
                if (i >= fieldNames.size()) {
                    break;
                }
                String value = matcher.group(i);
                String key = fieldNames.get(i - 1);
`

解决办法：
等于号可以去掉，因为下面代码 fieldNames.get(**i - 1**) 已经做了处理，不会造成数组越界

**Comment by liketic** [comment]
@likewindcai 已经fix
